# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms 
#will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

digits = [1,2]
acc = 0
(3..3999999).each do |n| 
  res = digits[0]+digits[1]
  if res%2 == 0
    acc += res  
  end
  digits.shift
  digits<<res
end
puts acc